Repository 2kodevs/Azul-Game, pull requests merged in 2020-04, with the labels that each got.

#10 Fixes #5 Basic strategy
  game.pl
  player.pl
  utils.pl
Labels: main

#12 Fixes #9 - Pipeline Implementation
  game.pl
  player.pl
  utils.pl
Labels: main

#16 Fixes #8 - Add unit tests
  .gitignore
  Makefile
  game.plt
  player.pl
  player.plt
  utils.plt
Labels: documentation, enhancement, test

#20 Fixes #15 - Add logs to project
  .gitignore
  Makefile
  game.pl
  logs.pl
  player.pl
  utils.pl
Labels: main

#19 Fixes #2 - Documentation
  README.md
  doc/Azul_instrucciones-pdf-espanol-castellano-juegos-mesa.pdf
  doc/Orientación de Proyecto de Prolog.docx
Labels: documentation

#18 Fixes #17 - Makefile parameters
  Makefile
  game.pl
  logs.pl
  utils.pl
Labels: enhancement

#21 Fixes #11 - Add new strategies
  Makefile
  README.md
  game.pl
  game.plt
  logs.pl
  player.pl
  utils.pl
Labels: main

#25 Fixes #22 - Add project's report
  .gitignore
  doc/Informe.pdf
Labels: documentation
